### ISSUE TITLE
Support and test on MacOS

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-inveniordm#24]
Currently the package has been designed for and tested on Linux only.

**Comment by douglowe** [comment]
RO-Crate InvenioRDM Deposit tool.

**Comment by douglowe** [comment]
@elichad - an update on progress:

1. I installed via pip on OSX. This works. My python version is 3.11
2. I then naively downloaded an RO-Crate from workflowhub, and tried to use this tool to push it to the Zenodo Sandbox (using the command `rocrate_inveniordm <directory>`). This is giving me the below error:
```
|- Applying rule collection creators_mapping
		|- Getting paths for $author[].affiliation[]
Traceback (most recent call last):
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/bin/rocrate_inveniordm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/deposit.py", line 84, in main
    deposit(
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/deposit.py", line 169, in deposit
    data_cite_metadata = converter.convert(
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/mapping/converter.py", line 78, in convert
    mapping_paths = get_mapping_paths(rc, mappings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/mapping/converter.py", line 131, in get_mapping_paths
    mapping_paths[i] = get_paths(rc, i)
                       ^^^^^^^^^^^^^^^^
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/mapping/converter.py", line 230, in get_paths
    temp = rc_get_rde(rc)
           ^^^^^^^^^^^^^^
  File "/Users/user/work/manchester/eScience/rocrates/rocrate-inveniordm-test/venv/lib/python3.11/site-packages/rocrate_inveniordm/mapping/crate_utils.py", line 53, in rc_get_rde
    and conformsTo.get("@id")
        ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

I realise that I probably should have started with a simpler, more known, RO-Crate first. I will also try the tests bundled with inveniordm, to make sure they all pass successfully.

**Comment by douglowe** [comment]
The tests provided with the source code mostly pass for me. One is skipped, and another is xpassed:
```
...
test/unit/test_conditions.py::test_geonames SKIPPED (condition not implemented)
...
test/unit/test_mapping_utils.py::test_contains_atatthis__dict_later_item XPASS (uncertain on intended design of function. TODO review this)
```

**Comment by elichad** [comment]
@douglowe the error you found is a bug (not OS-specific) which I've just documented here: https://github.com/ResearchObject/ro-crate-inveniordm/issues/41.

So it sounds like the package is working the same on MacOS as it is on Linux.

I would like to get MacOS added to the [CI tests](https://github.com/ResearchObject/ro-crate-inveniordm/blob/main/.github/workflows/test.yml) too - would you have time to add it to the build matrix and add the necessary install steps?
